## Numpy - Numerical Python

* Numpy has been used behind  pandas, tensorflow,scikit learn
* less memory,more time efficient
* to avoid loop



In [1]:
a = [6, 7, 8, 9]
a, type(a)

([6, 7, 8, 9], list)

In [2]:
# to find the list multiples of 3
a * 3  # repeat

[6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9]

In [3]:
out = [i*3 for i in a]

In [4]:
out

[18, 21, 24, 27]

In [6]:
import numpy as np
a = np.array([2,3,4])
a, type(a)

(array([2, 3, 4]), numpy.ndarray)

In [7]:
a * 4

array([ 8, 12, 16])

In [8]:
a = [4, 9.7, '7.8']    # it has multiple data types
for i in a:
    print(i, type(i))

4 <class 'int'>
9.7 <class 'float'>
7.8 <class 'str'>


In [10]:
arr = np.array(a)   # covert list into arrayit has all value as string
for i in arr:
    print(i, type(i))

4 <class 'numpy.str_'>
9.7 <class 'numpy.str_'>
7.8 <class 'numpy.str_'>


In [15]:
a = [4, 9.7] 
b = np.array(a)
for i in b:
    print(i, type(i))

4.0 <class 'numpy.float64'>
9.7 <class 'numpy.float64'>


In [17]:
# default datatype - float
# str
# complex
# integer

In [22]:
b = [2, 5.6, 5+8j]
for i in b:
    print(i, type(i))


2 <class 'int'>
5.6 <class 'float'>
(5+8j) <class 'complex'>


In [23]:
b = np.array(b)   # it has all value as string
for i in b:
    print(i, type(i))

(2+0j) <class 'numpy.complex128'>
(5.6+0j) <class 'numpy.complex128'>
(5+8j) <class 'numpy.complex128'>


In [46]:
a

array(['4', 'hguy', '(9+1j)'], dtype='<U64')

In [11]:
emp = np.array([])
emp

array([], dtype=float64)

In [12]:
# to create array
a = np.array([[1,2,3],[5,6,7],[0,2,1]])
a

array([[1, 2, 3],
       [5, 6, 7],
       [0, 2, 1]])

In [13]:
a.shape

(3, 3)

In [14]:
# to create array
a = np.array([[1,2,3],[5,6,7]])
a, a.shape

(array([[1, 2, 3],
        [5, 6, 7]]),
 (2, 3))

In [15]:
a = np.array([[1,2],[6,7],[4,7]])
a

array([[1, 2],
       [6, 7],
       [4, 7]])

In [16]:
a.shape

(3, 2)

In [17]:
# n dimention
a.ndim # 2 --> dataframe, 1 ---> series

2

In [23]:
b = np.array([8, 9, 0])
b, b.ndim   # --- > series

(array([8, 9, 0]), 1)

In [25]:
a = [1,3,5]  # list
b = np.array([1,3,5])  # array
print(a is b), id(a), id(b)

False


(None, 2936783651840, 2936780830928)

In [34]:
a = np.array([1,2,3])
id(a)

2342488550608

In [27]:
a,b = [1, 2, 4], np.array([1,8,0])
a,b
id(a), id(b)

(2936783719680, 2936780831024)

In [28]:
for i in zip(a,b):
    print(i)

(1, 1)
(2, 8)
(4, 0)


In [39]:
print(id(a), id(b))

2342622323712 2342488552144


In [40]:
id(a[0]), id(b[0])

(140710246081320, 2342622363600)

In [29]:
for i,j in zip(a,b):
    print(id(i),id(j))

140729209971496 2936778996752
140729209971528 2936778996464
140729209971592 2936778996944


In [42]:
b = np.array([1, 3, 5, 7])
b

array([1, 3, 5, 7])

In [43]:
a = np.array([[1,5],[9,3]])

In [44]:
a

array([[1, 5],
       [9, 3]])

In [18]:
# Reshape
a = np.array([[2,3,6],[1,2,8]])
b = np.array([[3,6],[1,7]])
a,b, a.shape, b.shape         

(array([[2, 3, 6],
        [1, 2, 8]]),
 array([[3, 6],
        [1, 7]]),
 (2, 3),
 (2, 2))

In [19]:
a * b   #(2,3)(3,2)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [20]:
c = a.reshape(3,2)
c, c.shape

(array([[2, 3],
        [6, 1],
        [2, 8]]),
 (3, 2))

In [38]:
# append
emp = np.array([])
emp = np.append(emp,1)
emp = np.append(emp,3)
emp = np.append(emp,5)
emp            #default float

array([1., 3., 5.])

In [39]:
# typecasting
# create empty array and change the data type
# method 1
d1 = np.array([], dtype = int)
d1

array([], dtype=int32)

In [40]:
d1 = np.append(d1,1) 
d1 = np.append(d1,3)
d1            

array([1, 3])

In [41]:
# method 2 
d1.astype(str)

array(['1', '3'], dtype='<U11')

In [21]:
# slicing   rowstart:rowend, columnstart:columnend,  end=n-1
a = np.array([[1,2,3],[5,6,7],[4,5,8]])
a


array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 8]])

In [22]:
a[1:,:2]

array([[5, 6],
       [4, 5]])

In [46]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [47]:
a[0:2,1:]

array([[2, 3],
       [6, 7]])

In [64]:
a[0:2, 0:2], a[1:,1:]

(array([[1, 2],
        [5, 6]]),
 array([[6, 7],
        [5, 8]]))

In [48]:
a[:,:2]    

array([[1, 2],
       [5, 6],
       [4, 5]])

In [49]:
a[1:,1:]

array([[6, 7],
       [5, 8]])

In [87]:
a[0:3,0:2]

array([[1, 2],
       [5, 6],
       [4, 5]])

### full, ones, zeros

In [23]:
# Zero matrix
np.zeros([2,3]) # shape (row, column)


array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros([3,2])-8 # add, sub

array([[-8., -8.],
       [-8., -8.],
       [-8., -8.]])

In [25]:
# ones
np.ones([3,4])  # shape (row, column)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# ones
np.ones([3,4])*7 # add, sub, mul, div

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [27]:
# full
np.full([3,1])  # shape (row, column)


TypeError: full() missing 1 required positional argument: 'fill_value'

In [28]:
#full
np.full([3,1], 6)

array([[6],
       [6],
       [6]])

In [29]:
a1 = np.ones([4,4],dtype=int)
a1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
a1[1:2,2:] = 8
a1

array([[1, 1, 1, 1],
       [1, 1, 8, 8],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
a1[0:2,2:] = 6
a1

array([[1, 1, 6, 6],
       [1, 1, 6, 6],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
# identity matrix
a1 = np.eye(5) # shape (rowcol)
a1 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
# identity matrix
a1 = np.eye(2)  # shape (rowcol)
a1 * 5

array([[5., 0.],
       [0., 5.]])

In [36]:
a2 = np.eye(3,4)
a2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [39]:
# random change
np.arange(0,11).reshape(3,3) #arrange(start, end)

ValueError: cannot reshape array of size 11 into shape (3,3)

In [79]:
# random change
np.arange(0,4).reshape(2,2) #arrange(start, end)

array([[0, 1],
       [2, 3]])

In [40]:
np.arange(5,14).reshape(3,3) 

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [41]:
# lin space
np.linspace(1,100) #start,end, count  # default = 50

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [42]:
# linespace
np.linspace(1,100, 80, dtype=int) #start,end, count  

array([  1,   2,   3,   4,   6,   7,   8,   9,  11,  12,  13,  14,  16,
        17,  18,  19,  21,  22,  23,  24,  26,  27,  28,  29,  31,  32,
        33,  34,  36,  37,  38,  39,  41,  42,  43,  44,  46,  47,  48,
        49,  51,  52,  53,  54,  56,  57,  58,  59,  61,  62,  63,  64,
        66,  67,  68,  69,  71,  72,  73,  74,  76,  77,  78,  79,  81,
        82,  83,  84,  86,  87,  88,  89,  91,  92,  93,  94,  96,  97,
        98, 100])

In [43]:
np.linspace(1000, 5000, 200)

array([1000.        , 1020.10050251, 1040.20100503, 1060.30150754,
       1080.40201005, 1100.50251256, 1120.60301508, 1140.70351759,
       1160.8040201 , 1180.90452261, 1201.00502513, 1221.10552764,
       1241.20603015, 1261.30653266, 1281.40703518, 1301.50753769,
       1321.6080402 , 1341.70854271, 1361.80904523, 1381.90954774,
       1402.01005025, 1422.11055276, 1442.21105528, 1462.31155779,
       1482.4120603 , 1502.51256281, 1522.61306533, 1542.71356784,
       1562.81407035, 1582.91457286, 1603.01507538, 1623.11557789,
       1643.2160804 , 1663.31658291, 1683.41708543, 1703.51758794,
       1723.61809045, 1743.71859296, 1763.81909548, 1783.91959799,
       1804.0201005 , 1824.12060302, 1844.22110553, 1864.32160804,
       1884.42211055, 1904.52261307, 1924.62311558, 1944.72361809,
       1964.8241206 , 1984.92462312, 2005.02512563, 2025.12562814,
       2045.22613065, 2065.32663317, 2085.42713568, 2105.52763819,
       2125.6281407 , 2145.72864322, 2165.82914573, 2185.92964

In [44]:
# concatenate:   --> axis = 0(row), ---> axis = 1(column) 
a = np.full([3,3],5)
b = np.full([3,3],6)
a,b

(array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]),
 array([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]))

In [45]:
np.concatenate([a,b]) # rowwise conncatenate #default axis = 0

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [46]:
np.concatenate([a,b], axis=1) # columnwise concatenate  


array([[5, 5, 5, 6, 6, 6],
       [5, 5, 5, 6, 6, 6],
       [5, 5, 5, 6, 6, 6]])

In [47]:
# Ex-2
x = np.array([[1,2,3],[5,6,7]])
y = np.array([[4,4,5],[8,8,7]])
x, y, x.shape, y.shape

(array([[1, 2, 3],
        [5, 6, 7]]),
 array([[4, 4, 5],
        [8, 8, 7]]),
 (2, 3),
 (2, 3))

In [48]:
z = np.concatenate([x,y]) 
z, z.shape

(array([[1, 2, 3],
        [5, 6, 7],
        [4, 4, 5],
        [8, 8, 7]]),
 (4, 3))

In [49]:
z = np.concatenate([x,y], axis = 1) 
z, z.shape

(array([[1, 2, 3, 4, 4, 5],
        [5, 6, 7, 8, 8, 7]]),
 (2, 6))

In [50]:
a, a.shape


(array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]),
 (3, 3))

In [51]:
a = np.array([[1,2,3],[6,2,5]])
a, a.shape

(array([[1, 2, 3],
        [6, 2, 5]]),
 (2, 3))

In [53]:
# transporse
a = np.array([[1,5,9],[7,6,5]])
b = a.T
a, a.shape, b, b.shape

(array([[1, 5, 9],
        [7, 6, 5]]),
 (2, 3),
 array([[1, 7],
        [5, 6],
        [9, 5]]),
 (3, 2))

In [54]:
z, z.shape

(array([[1, 2, 3, 4, 4, 5],
        [5, 6, 7, 8, 8, 7]]),
 (2, 6))

In [55]:
c = z.T
c, c.shape

(array([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8],
        [4, 8],
        [5, 7]]),
 (6, 2))

In [56]:
# random.random -->  No duplicates (repeated)
a = np.random.random(15) # without range  
a

array([0.7380464 , 0.84761079, 0.19985114, 0.00284315, 0.80067114,
       0.02526332, 0.08070016, 0.9403238 , 0.42366178, 0.59130314,
       0.55212825, 0.84011837, 0.73058405, 0.24966327, 0.62422641])

In [58]:
# random.randint  --> It has duplicates
np.random.randint(1, 5, 15) #start, end, count

array([1, 2, 3, 2, 3, 4, 4, 1, 2, 3, 2, 2, 4, 2, 1])

In [59]:
## shallow copy
old = np.eye(3)
new = old  # shallow copy
old, new

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [60]:
new [1,2] = 7

In [61]:
new

array([[1., 0., 0.],
       [0., 1., 7.],
       [0., 0., 1.]])

In [62]:
old

array([[1., 0., 0.],
       [0., 1., 7.],
       [0., 0., 1.]])

In [63]:
#deep copy
new1 = old.copy() # slicing not work in numpy
new1

array([[1., 0., 0.],
       [0., 1., 7.],
       [0., 0., 1.]])

### Trigonometry

In [64]:
matrix = np.array([[2,3,5], [8,0,8]])
matrix

array([[2, 3, 5],
       [8, 0, 8]])

In [65]:
np.sin(matrix)

array([[ 0.90929743,  0.14112001, -0.95892427],
       [ 0.98935825,  0.        ,  0.98935825]])

In [66]:
np.cos(matrix)

array([[-0.41614684, -0.9899925 ,  0.28366219],
       [-0.14550003,  1.        , -0.14550003]])

In [67]:
np.sqrt(matrix)

array([[1.41421356, 1.73205081, 2.23606798],
       [2.82842712, 0.        , 2.82842712]])

In [68]:
np.sum(matrix)

26

In [69]:
np.mean(matrix)

4.333333333333333

In [70]:
np.median(matrix)

4.0

In [71]:
np.min(matrix)

0

In [72]:
np.max(matrix)

8

In [73]:
np.std(matrix)

2.981423969999719

In [74]:
# useful method
# np.nan
# np.where
# np.select

In [75]:
z = np.full([3,3],3, dtype=int)
z

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [76]:
z = z.astype(int)

In [77]:
z[:,2] = np.nan

ValueError: cannot convert float NaN to integer

In [80]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'D:\Greens technologies\Python\Notebook\Data\dummy1.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Greens technologies\\Python\\Notebook\\Data\\dummy1.csv'

In [49]:
df = pd.read_excel(r'D:\Greens technologies\Python\Notebook\Data\dummy.xlsx')
df

id name product
0  a  xyz       x
1  b  abc     NaN
2  c  zzz       c
3  d   as     NaN
4  e  www       b

In [50]:
## np.where( condition, true,false)

df['Null_column'] = np.where(df['product'].isna(),'Yes','No')
df

id name product Null_column
0  a  xyz       x          No
1  b  abc     NaN         Yes
2  c  zzz       c          No
3  d   as     NaN         Yes
4  e  www       b          No

In [51]:
## np.where( conditin, true,false)

df['Another_product'] = np.where(df['product'].isna(),df['name'],df['product'])
df

id name product Null_column Another_product
0  a  xyz       x          No               x
1  b  abc     NaN         Yes             abc
2  c  zzz       c          No               c
3  d   as     NaN         Yes              as
4  e  www       b          No               b